# theme: jekyll-theme-cayman
title: Zean Qin
description: Welcome to my personal website

highlighter: rouge

##### BUILD SETTINGS #####
# incremental: true

# strip all unncessary whitespace and comments
# http://jch.penibelst.de/
compress_html:
  blanklines: true